steps:
# Install dependencies
- name: node:10.16.0
  entrypoint: npm
  args: ['install']
# Run tests
- name: node:10.16.0
  entrypoint: npm
  args: ['test']
# Run custom commands
- name: node:10.16.0
  entrypoint: npm
  args: ['run', 'build']
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/pipelinedemoapp:${SHORT_SHA}', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/pipelinedemoapp']
  # deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'pipelinedemoapp', '--image', 'gcr.io/$PROJECT_ID/pipelinedemoapp:${SHORT_SHA}', '--region', 'us-central1', '--allow-unauthenticated', '--platform', 'managed']
  env:
  - 'PORT=8080'
images:
- gcr.io/$PROJECT_ID/pipelinedemoapp